export const GAME = {
  MAX_GAME_LIMIT: 50,
  DEFAULT_FILTERS: {
    sortBy: 'releaseDate',
    sortOrder: 'desc',
    limit: 50,
  },
  GAME_FIELDS: [
    'igdb_id',
    'rawg_id',
    'title',
    'slug',
    'summary',
    'storyline',
    'rating',
    'aggregated_rating',
    'total_rating',
    'hypes',
    'first_release_date',
    'cover',
    'genres',
    'platforms',
    'themes',
    'provider',
    'url',
    'updatedAt',
    'createdAt',
  ],
  GAME_SORT_FIELDS: ['title', 'releaseDate', 'rating'],
} as const
