import { z } from 'zod'
import { IdListSchema } from '../base/IdListSchema.ts'
import { IdSchema } from '../base/IdSchema.ts'

/**
 * **GameSchema**
 *
 * Zod schema defining the **domain-neutral representation** of a game entity.
 *
 * ### Purpose
 * Serves as the canonical game model across all providers (IGDB, RAWG, Steam, etc.),
 * ensuring a consistent structure for storing, transforming, and exposing game data
 * within the application domain.
 *
 * ### Behavior
 * - Provider-agnostic — no provider-specific fields or naming conventions.
 * - Accepts optional or nullable fields to support partial provider data.
 * - Includes normalized identifiers, metadata, and timestamps for auditing.
 *
 * ### Fields
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `id` | `number?` | Optional internal numeric ID (generated by DB or domain logic). |
 * | `providerIds` | `{ igdb?: number?, rawg?: number? }` | Cross-provider identifiers. |
 * | `title` | `string` | Canonical title of the game. |
 * | `slug` | `string` | URL-friendly version of the title. |
 * | `summary` | `string?` | Short description or overview. |
 * | `storyline` | `string?` | Narrative or story-related description. |
 * | `rating` | `number?` | Average user rating (0–100). |
 * | `aggregated_rating` | `number?` | Weighted aggregate rating from external sources. |
 * | `total_rating` | `number?` | Combined or computed rating metric. |
 * | `hypes` | `number?` | Pre-release popularity indicator (if available). |
 * | `first_release_date` | `Date?` | Original release date. |
 * | `cover` | `number?` | ID or index of the game’s cover asset. |
 * | `genres` | `number[]?` | IDs of associated genres. |
 * | `platforms` | `number[]?` | IDs of supported platforms. |
 * | `themes` | `number[]?` | IDs of thematic tags. |
 * | `url` | `string?` | Canonical external link (e.g., IGDB or RAWG page). |
 * | `updatedAt` | `Date?` | Last update timestamp. |
 * | `createdAt` | `Date?` | Creation timestamp. |
 *
 * @see {@link IdSchema}
 * @see {@link IdListSchema}
 */
export const GameSchema = z.object({
  id: IdSchema.optional(),
  providerIds: z.object({
    igdb: IdSchema.nullable().optional(),
    rawg: IdSchema.nullable().optional(),
  }),
  title: z.string(),
  slug: z.string(),
  summary: z.string().nullable().optional(),
  storyline: z.string().nullable().optional(),
  rating: z.number().nullable().optional(),
  aggregated_rating: z.number().nullable().optional(),
  total_rating: z.number().nullable().optional(),
  hypes: z.number().int().nullable().optional(),
  first_release_date: z.date().nullable().optional(),
  cover: z.number().int().nullable().optional(),
  genres: IdListSchema.optional(),
  platforms: IdListSchema.optional(),
  themes: IdListSchema.optional(),
  url: z.url().nullable().optional(),
  updatedAt: z.date().optional(),
  createdAt: z.date().optional(),
})
