import { z } from 'zod'

/**
 * **JWTJtiSchema**
 *
 * Zod schema representing the **JWT ID (`jti`) claim**, a globally unique
 * identifier assigned to each token.
 *
 * ### Purpose
 * Ensures every issued token has a unique, verifiable identifier that can be
 * used for **revocation tracking** and **blacklist lookups**.
 *
 * ### Behavior
 * - Must be a valid [RFC 4122](https://datatracker.ietf.org/doc/html/rfc4122) UUID string.
 * - Guarantees uniqueness across all tokens generated by the system.
 * - Used as the primary key for revocation entries in Redis or other storage.
 *
 * @see {@link https://datatracker.ietf.org/doc/html/rfc4122 | RFC 4122}
 */
export const JWTJtiSchema = z.uuid()
